#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : trurl
Version  : 0.2
Release  : 1
URL      : https://github.com/curl/trurl/archive/refs/tags/trurl-0.2.tar.gz
Source0  : https://github.com/curl/trurl/archive/refs/tags/trurl-0.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: trurl-license = %{version}-%{release}
BuildRequires : curl-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# trurl
command line tool for URL parsing and manipulation
[original idea](https://curl.se/mail/archive-2023-03/0030.html)

%package license
Summary: license components for the trurl package.
Group: Default

%description license
license components for the trurl package.


%prep
%setup -q -n trurl-trurl-0.2
cd %{_builddir}/trurl-trurl-0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1680556492
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1680556492
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/trurl
cp %{_builddir}/trurl-trurl-%{version}/COPYING %{buildroot}/usr/share/package-licenses/trurl/ee07057bbf567b3d4925a32a37148a7cbf422acd || :
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/trurl/ee07057bbf567b3d4925a32a37148a7cbf422acd
